.catalog:
  name: "Sameersbn BIND DNS & Webmin"
  version: "v1.0.0-rancher1"
  description: "Domain Name Server powered by Bind & Webmin"
  minimum_rancher_version: v0.44.0
  #maximum_rancher_version: v1.2.0-pre3
  questions:
      - variable: "bind_port"
      label: "Bind port"
      description: "Bind port to expose on host. Will be used to bind both TCP and UDP"
      type: "string"
      default: 53
      required: true
      - variable: "webmin_port"
      label: "Webmin port"
      description: "Webmin port to expose on host. Will be used to webmin TCP"
      type: "string"
      default: 10000
      required: true
      - variable: "bind_volume_data"
      label: "The volume path for bind service"
      description: "The volume path for bind service"
      type: "string"
      default: "/my/custom/data"
      required: true
bind:
  scale: 1
  health_check:
    port: ${bind_port}
    interval: 2000
    initializing_timeout: 20000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 2
    response_timeout: 2000
